INSERT INTO USUARIO (EMAIL, SENHA, DATA_CRIACAO_USUARIO)
VALUES ('USUARIO1@GMAIL.COM', 'USUARIO1', TO_DATE('06/04/2022','DD/MM/YYYY')
); 

INSERT INTO USUARIO (EMAIL, SENHA, DATA_CRIACAO_USUARIO)
VALUES ('USUARIO2@GMAIL.COM', 'USUARIO2', TO_DATE('06/04/2022','DD/MM/YYYY')
);

INSERT INTO USUARIO (EMAIL, SENHA, DATA_CRIACAO_USUARIO)
VALUES ('USUARIO3@GMAIL.COM', 'USUARIO3', TO_DATE('06/04/2022','DD/MM/YYYY')
);

INSERT INTO USUARIO (EMAIL, SENHA, DATA_CRIACAO_USUARIO)
VALUES ('USUARIO4@GMAIL.COM', 'USUARIO4', TO_DATE('06/04/2022','DD/MM/YYYY')
);

INSERT INTO USUARIO (EMAIL, SENHA, DATA_CRIACAO_USUARIO)
VALUES ('USUARIO5@GMAIL.COM', 'USUARIO5', TO_DATE('06/04/2022','DD/MM/YYYY')
);

INSERT INTO USUARIO (EMAIL, SENHA, DATA_CRIACAO_USUARIO)
VALUES ('USUARIO6@GMAIL.COM', 'USUARIO6', TO_DATE('06/04/2022','DD/MM/YYYY')
);