INSERT INTO USUARIO (EMAIL, SENHA, DATA_CRIACAO_USUARIO)
VALUES ('USUARIO1@GMAIL.COM', 'USUARIO1', TO_DATE('06/04/2022','DD/MM/YYYY')
); 

INSERT INTO USUARIO (EMAIL, SENHA, DATA_CRIACAO_USUARIO)
VALUES ('USUARIO2@GMAIL.COM', 'USUARIO2', TO_DATE('06/04/2022','DD/MM/YYYY')
);

INSERT INTO USUARIO (EMAIL, SENHA, DATA_CRIACAO_USUARIO)
VALUES ('USUARIO3@GMAIL.COM', 'USUARIO3', TO_DATE('06/04/2022','DD/MM/YYYY')
);

INSERT INTO USUARIO (EMAIL, SENHA, DATA_CRIACAO_USUARIO)
VALUES ('USUARIO4@GMAIL.COM', 'USUARIO4', TO_DATE('06/04/2022','DD/MM/YYYY')
);

INSERT INTO USUARIO (EMAIL, SENHA, DATA_CRIACAO_USUARIO)
VALUES ('USUARIO5@GMAIL.COM', 'USUARIO5', TO_DATE('06/04/2022','DD/MM/YYYY')
);

INSERT INTO USUARIO (EMAIL, SENHA, DATA_CRIACAO_USUARIO)
VALUES ('USUARIO6@GMAIL.COM', 'USUARIO6', TO_DATE('06/04/2022','DD/MM/YYYY')
);

INSERT INTO ALUNO (NOME, CPF, RUA, NUM, BAIRRO, CIDADE, CEP, USUARIO)
VALUES ('Usuário 4', '13853147902', 'Rua Aqui Perto', '120', 'Saudade', 'São Paulo', '12348640', 4);

INSERT INTO ALUNO (NOME, CPF, RUA, NUM, BAIRRO, CIDADE, CEP, USUARIO)
VALUES ('Usuário 5', '46208834791', 'Rua Tal', '233', 'Parque Anhanguera', 'Belo Horizonte', '15688720', 5);

INSERT INTO ALUNO (NOME, CPF, RUA, NUM, BAIRRO, CIDADE, CEP, USUARIO)
VALUES ('Usuário 6', '51532770914', 'Rua Jardim Sul', '77', 'Nova Aliança', 'Campinas', '16672495', 6);